QUESTIONS = [
    # ── MODULE 1: Agentic AI Foundations ──────────────────────────────────────
    {
        "id": 101,
        "module": 1,
        "topic": "Agentic Properties",
        "question": "Which of the following best describes the 'goal-directed' property of an agentic system?",
        "options": [
            "A. The system can remember past interactions across sessions.",
            "B. The system pursues an objective through multiple steps rather than responding once.",
            "C. The system uses external APIs to fetch real-time data.",
            "D. The system generates a single high-quality response to a prompt.",
        ],
        "correct": "B",
        "explanation": "Goal-directed means the agent works toward an objective over multiple steps, not just a single response. Memory and tool use are separate properties.",
    },
    {
        "id": 102,
        "module": 1,
        "topic": "Agentic Properties",
        "question": "An AI system that calls a search API, reads the result, then decides to call a second API based on what it found is demonstrating which property?",
        "options": [
            "A. Memory-aware",
            "B. Goal-directed",
            "C. Tool-using",
            "D. Iterative",
        ],
        "correct": "C",
        "explanation": "Calling external APIs (search, databases, calculators) is the tool-using property. The system extends its capabilities beyond what the LLM alone can do.",
    },
    {
        "id": 103,
        "module": 1,
        "topic": "Agentic Properties",
        "question": "True or False: An agentic system that checks its own output and loops back to improve it is demonstrating the 'iterative' property.",
        "options": [
            "A. True",
            "B. False",
        ],
        "correct": "A",
        "explanation": "Iterative means the system can loop — generate, evaluate, and refine — rather than producing a single output and stopping.",
    },
    {
        "id": 104,
        "module": 1,
        "topic": "Core Components",
        "question": "Which of the six core components of an agentic system converts a plan into concrete actions?",
        "options": [
            "A. Planner",
            "B. Model",
            "C. Executor",
            "D. Evaluator",
        ],
        "correct": "C",
        "explanation": "The Executor carries out specific tasks — calling tools, writing files, making API requests. The Planner decides what to do; the Executor does it.",
    },
    {
        "id": 105,
        "module": 1,
        "topic": "Core Components",
        "question": "Which component determines whether the agent's goal has been satisfied and signals when to stop?",
        "options": [
            "A. Memory",
            "B. Planner",
            "C. Tools",
            "D. Evaluator",
        ],
        "correct": "D",
        "explanation": "The Evaluator assesses outputs against a success criterion and drives the loop decision: continue refining or stop and return the result.",
    },
    {
        "id": 106,
        "module": 1,
        "topic": "Core Components",
        "question": "In an agentic system, conversation history, retrieved facts, and intermediate results are all stored in which component?",
        "options": [
            "A. Tools",
            "B. Memory",
            "C. Executor",
            "D. Model",
        ],
        "correct": "B",
        "explanation": "Memory holds short-term context (conversation history), working state (intermediate results), and optionally long-term facts retrieved from external stores.",
    },
    {
        "id": 107,
        "module": 1,
        "topic": "The Agentic Loop",
        "question": "What is the correct order of the core agentic loop?",
        "options": [
            "A. Execute → Plan → Evaluate → Respond",
            "B. Plan → Execute → Evaluate → (loop or stop)",
            "C. Evaluate → Plan → Execute → Respond",
            "D. Prompt → Respond → Store → Repeat",
        ],
        "correct": "B",
        "explanation": "The agentic loop is: Plan (decompose the goal) → Execute (carry out steps) → Evaluate (check results) → loop back if the goal is not met, or stop and return.",
    },
    {
        "id": 108,
        "module": 1,
        "topic": "Single vs Agentic",
        "question": "Which of the following is a key difference between a single-turn LLM interaction and an agentic system?",
        "options": [
            "A. Agentic systems always produce longer responses.",
            "B. Single-turn systems cannot use the Claude API.",
            "C. Agentic systems make multiple LLM calls and can use tools across steps.",
            "D. Single-turn systems are always more accurate.",
        ],
        "correct": "C",
        "explanation": "The defining difference is multi-step orchestration and tool use. A single-turn system sends one prompt and gets one response; an agentic system orchestrates many calls with state in between.",
    },
    {
        "id": 109,
        "module": 1,
        "topic": "Core Components",
        "question": "The 'Model' component in an agentic architecture refers to:",
        "options": [
            "A. The database that stores agent outputs.",
            "B. The large language model that provides reasoning and generation.",
            "C. The orchestration framework (e.g., LangChain).",
            "D. The API gateway that routes requests.",
        ],
        "correct": "B",
        "explanation": "The Model is the LLM itself — it supplies reasoning, language understanding, and generation. All other components (Memory, Tools, Planner, Executor, Evaluator) are built around it.",
    },
    {
        "id": 110,
        "module": 1,
        "topic": "Agentic Properties",
        "question": "A customer service bot that only answers the current question with no access to prior conversation history is missing which agentic property?",
        "options": [
            "A. Tool-using",
            "B. Goal-directed",
            "C. Iterative",
            "D. Memory-aware",
        ],
        "correct": "D",
        "explanation": "Memory-aware means the system can recall prior context — conversation history, past decisions, retrieved facts. Without it, each turn starts from scratch.",
    },

    # ── MODULE 2: Prompt Fundamentals ─────────────────────────────────────────
    {
        "id": 201,
        "module": 2,
        "topic": "Prompt Framework",
        "question": "Which of the following lists all six elements of the structured prompt framework taught in Module 2?",
        "options": [
            "A. Goal, Steps, Examples, Tone, Format, Audience",
            "B. Role, Task, Context, Constraints, Output Format, Examples",
            "C. Persona, Goal, Tools, Memory, Evaluator, Output",
            "D. Instruction, System, User, Temperature, Model, Examples",
        ],
        "correct": "B",
        "explanation": "The six-element framework is: Role (who the model is), Task (what to do), Context (background information), Constraints (rules/limits), Output Format (how to structure the answer), Examples (demonstrations).",
    },
    {
        "id": 202,
        "module": 2,
        "topic": "Prompt Types",
        "question": "A prompt that begins 'You are a senior data analyst with 10 years of experience in SQL...' is primarily which type?",
        "options": [
            "A. Instruction prompt",
            "B. Role prompt",
            "C. Planning prompt",
            "D. Evaluation prompt",
        ],
        "correct": "B",
        "explanation": "A role prompt establishes the model's identity and persona. It shapes tone, expertise level, and reasoning style for everything that follows.",
    },
    {
        "id": 203,
        "module": 2,
        "topic": "Prompt Types",
        "question": "Which prompt type is used to classify an incoming message into one of several predefined categories so it can be sent to the right handler?",
        "options": [
            "A. Planning prompt",
            "B. Tool-use prompt",
            "C. Routing prompt",
            "D. Evaluation prompt",
        ],
        "correct": "C",
        "explanation": "A routing prompt asks the model to classify input (e.g., TECHNICAL / BILLING / GENERAL) so the orchestrator can direct it to the correct specialist or handler.",
    },
    {
        "id": 204,
        "module": 2,
        "topic": "Prompting Techniques",
        "question": "What is the key difference between zero-shot and few-shot prompting?",
        "options": [
            "A. Zero-shot uses a system prompt; few-shot does not.",
            "B. Zero-shot provides no examples; few-shot includes worked examples in the prompt.",
            "C. Few-shot is only used for classification tasks.",
            "D. Zero-shot always produces longer responses.",
        ],
        "correct": "B",
        "explanation": "Zero-shot relies on the model's pre-trained knowledge alone. Few-shot adds 1–5 worked examples in the prompt to demonstrate the desired input/output pattern.",
    },
    {
        "id": 205,
        "module": 2,
        "topic": "Prompting Techniques",
        "question": "Adding the phrase 'Think step by step' to a prompt is an example of which technique?",
        "options": [
            "A. Few-shot prompting",
            "B. Role prompting",
            "C. Chain-of-thought prompting",
            "D. Output format specification",
        ],
        "correct": "C",
        "explanation": "Chain-of-thought (CoT) prompting elicits intermediate reasoning steps. 'Think step by step' is the canonical zero-shot CoT trigger that dramatically improves performance on reasoning tasks.",
    },
    {
        "id": 206,
        "module": 2,
        "topic": "Prompt Framework",
        "question": "Which element of the six-element prompt framework prevents the model from doing things you don't want — such as speculating, going off-topic, or exceeding a word count?",
        "options": [
            "A. Role",
            "B. Context",
            "C. Constraints",
            "D. Examples",
        ],
        "correct": "C",
        "explanation": "Constraints set explicit rules: 'Do not speculate', 'Respond in under 100 words', 'Only use the provided data'. They act as guardrails on model behaviour.",
    },
    {
        "id": 207,
        "module": 2,
        "topic": "Prompt Types",
        "question": "True or False: A planning prompt is used to break a complex goal into an ordered list of subtasks the model should follow.",
        "options": [
            "A. True",
            "B. False",
        ],
        "correct": "A",
        "explanation": "A planning prompt asks the model to decompose a high-level goal into concrete, ordered steps — the foundation of the Planner agent component.",
    },
    {
        "id": 208,
        "module": 2,
        "topic": "Refinement Loops",
        "question": "In a generate → critique → rewrite loop, what is the role of the Critic prompt?",
        "options": [
            "A. To produce the initial draft of the content.",
            "B. To evaluate the draft against specific criteria and provide scored feedback.",
            "C. To route the output to the correct specialist.",
            "D. To call an external tool to validate the content.",
        ],
        "correct": "B",
        "explanation": "The Critic prompt evaluates the generated output — scoring it on criteria like clarity, accuracy, and completeness — and returns actionable feedback for the Rewriter to act on.",
    },
    {
        "id": 209,
        "module": 2,
        "topic": "Prompt Types",
        "question": "Which prompt type tells the model that it has access to a web search function and describes how to use it?",
        "options": [
            "A. Routing prompt",
            "B. Instruction prompt",
            "C. Tool-use prompt",
            "D. Evaluation prompt",
        ],
        "correct": "C",
        "explanation": "A tool-use prompt describes the external tools available to the agent — their names, parameters, and when to invoke them — enabling the model to decide when and how to call them.",
    },
    {
        "id": 210,
        "module": 2,
        "topic": "Prompt Framework",
        "question": "A prompt that tells the model to 'return a JSON object with keys: summary, sentiment, action_items' is specifying which element?",
        "options": [
            "A. Constraints",
            "B. Examples",
            "C. Output Format",
            "D. Task",
        ],
        "correct": "C",
        "explanation": "Output Format defines the structure of the model's response — prose, bullet list, JSON schema, table, etc. Specifying it dramatically increases consistency and parseability.",
    },

    # ── MODULE 3: Agent Types and Components ──────────────────────────────────
    {
        "id": 301,
        "module": 3,
        "topic": "Agent Components",
        "question": "Which of the four agent components maps directly to the 'system' parameter in the Claude API call?",
        "options": [
            "A. Knowledge",
            "B. Tools",
            "C. Interaction Layer",
            "D. Persona",
        ],
        "correct": "D",
        "explanation": "Persona defines the agent's identity, role, and tone. In code, this is passed as the system prompt — the foundational instruction that shapes all model behaviour.",
    },
    {
        "id": 302,
        "module": 3,
        "topic": "Agent Components",
        "question": "Domain-specific facts, retrieved documents, and background knowledge injected into the prompt are all part of which agent component?",
        "options": [
            "A. Interaction Layer",
            "B. Knowledge",
            "C. Tools",
            "D. Persona",
        ],
        "correct": "B",
        "explanation": "Knowledge is the context the agent draws on — static documents, retrieved chunks from a vector store, or structured data injected into the message. It gives the agent something to reason over.",
    },
    {
        "id": 303,
        "module": 3,
        "topic": "Agent Types",
        "question": "A support request arrives and an agent reads it, then outputs 'TECHNICAL' so it can be sent to the right team. This agent is a:",
        "options": [
            "A. Planner",
            "B. Executor",
            "C. Router",
            "D. Critic",
        ],
        "correct": "C",
        "explanation": "A Router classifies input into predefined categories or routes. Its output is a label, not a result — it tells the orchestrator where to send work next.",
    },
    {
        "id": 304,
        "module": 3,
        "topic": "Agent Types",
        "question": "Which agent type takes a high-level goal and returns an ordered list of subtasks for other agents to execute?",
        "options": [
            "A. Executor",
            "B. Orchestrator",
            "C. Retriever",
            "D. Planner",
        ],
        "correct": "D",
        "explanation": "The Planner decomposes a goal into steps. It does not execute the steps — it produces a plan that Executors act on. Think of it as the architect, not the builder.",
    },
    {
        "id": 305,
        "module": 3,
        "topic": "Agent Types",
        "question": "True or False: A Specialist agent is designed to handle any type of task with general-purpose capability.",
        "options": [
            "A. True",
            "B. False",
        ],
        "correct": "B",
        "explanation": "A Specialist is a domain expert — it handles a narrow, specific type of task very well (e.g., SQL generation, legal clause review). It is the opposite of a generalist agent.",
    },
    {
        "id": 306,
        "module": 3,
        "topic": "Agent Types",
        "question": "An agent that queries a knowledge base, finds the three most relevant chunks, and passes them to an answering agent is called a:",
        "options": [
            "A. Critic",
            "B. Planner",
            "C. Retriever",
            "D. Orchestrator",
        ],
        "correct": "C",
        "explanation": "A Retriever searches a knowledge source — vector database, document store, web search — and returns the most relevant context. It enables RAG (Retrieval-Augmented Generation) patterns.",
    },
    {
        "id": 307,
        "module": 3,
        "topic": "Agent Types",
        "question": "Which agent type coordinates a team of specialist agents, delegates subtasks, and synthesises their outputs into a final result?",
        "options": [
            "A. Router",
            "B. Orchestrator",
            "C. Executor",
            "D. Critic",
        ],
        "correct": "B",
        "explanation": "The Orchestrator is the project manager of multi-agent systems. It decides which specialists to invoke, in what order, and how to combine their outputs — without doing the specialist work itself.",
    },
    {
        "id": 308,
        "module": 3,
        "topic": "Agent Types",
        "question": "Which agent type reviews a generated output and returns a score plus actionable feedback for improvement?",
        "options": [
            "A. Executor",
            "B. Router",
            "C. Critic",
            "D. Retriever",
        ],
        "correct": "C",
        "explanation": "The Critic evaluates quality against criteria (accuracy, clarity, completeness) and produces structured feedback. It drives the evaluator-optimizer loop that improves outputs iteratively.",
    },
    {
        "id": 309,
        "module": 3,
        "topic": "Agent Components",
        "question": "External functions like a web search API, a calculator, or a code interpreter that an agent can invoke are captured in which component?",
        "options": [
            "A. Knowledge",
            "B. Tools",
            "C. Interaction Layer",
            "D. Persona",
        ],
        "correct": "B",
        "explanation": "Tools are the external capabilities an agent can call — APIs, functions, databases. They are described to the model via tool-use prompts so the model knows when and how to invoke them.",
    },
    {
        "id": 310,
        "module": 3,
        "topic": "Agent Components",
        "question": "When designing a 3-agent team for document analysis (summarise, assess risk, write report), which agent type is best suited to coordinate the other two and produce the final deliverable?",
        "options": [
            "A. Critic",
            "B. Retriever",
            "C. Router",
            "D. Orchestrator",
        ],
        "correct": "D",
        "explanation": "An Orchestrator manages multi-agent collaboration — it calls the Summariser, passes output to the Risk Assessor, then combines both results into a final report. It is the coordination layer.",
    },
]
